### ISSUE TITLE
Settings and stored words get lost when the app is closed

### ISSUE THREAD

**Issue by Sami-Perkele** [amilcarsantos/harbour-bigwordz#2]
On the latest Sailfish OS version, 1.1.9.28, settings and stored words are forgotten when I close the application.

**Comment by amilcarsantos** [comment]
Question: When opening and stored words are forgotten, does the 'preview' background becomes just a thin bar (instead of occupying the screen width)?

**Comment by Sami-Perkele** [comment]
I don't know what you mean by "preview background". I would guess the problem is that the words do not actually get stored to any file. Only to memory.

**Comment by amilcarsantos** [comment]
I'm just trying to understand if is the same issue than another previously reported, where one of the settings (some times) fails to load and consequently skips the loading of the stored words... Another consequence was (in the edit mode) the background of the big words preview to shirk to a vertical bar.

**Comment by Sami-Perkele** [comment]
I don't seem to have any other problem. Only that the settings are never (re)stored. Background works normally.

**Comment by Sami-Perkele** [comment]
Hmm. I seem to have corrected the problem myself just now. I changed some settings, then closed the application and now the stored works restored.

**Comment by amilcarsantos** [comment]
In v0.7 (approved today in harbour) I've improved the load/save settings. Thus this issue should be fixed.
